/**
 * @auth/protocol — EU AI Act Article 50 compliance
 *
 * Article 50 of the EU AI Act requires that AI-generated or AI-manipulated
 * content be clearly labeled in a machine-readable way. Enforcement begins
 * August 2, 2026.
 *
 * This module provides:
 * 1. Compliance labeling — generates machine-readable compliance metadata
 *    from a credential's AI assistance level
 * 2. Compliance checking — verifies that content has proper labeling
 * 3. Article 50-specific credential types — wraps content credentials
 *    with compliance metadata
 */

import type {
  SignedCredential,
  AIAssistanceLevel,
} from "./types.js";
import {
  verifyCredentialSignature,
} from "./credentials.js";

// ── Compliance Types ──────────────────────────────────────────────

/** Article 50 label categories */
export type Article50Label =
  | "human-only"
  | "ai-assisted"
  | "ai-generated"
  | "ai-fully-generated"
  | "deepfake"
  | "ai-manipulated";

/** Machine-readable compliance metadata */
export interface ComplianceLabel {
  label: Article50Label;
  description: string;
  aiAssistance: AIAssistanceLevel;
  requiresDisclosure: boolean;
  labeledAt: string;
  protocolVersion: string;
}

/** Result of a compliance check */
export interface ComplianceResult {
  compliant: boolean;
  label: ComplianceLabel | null;
  violations: string[];
  credential: SignedCredential | null;
  checkedAt: string;
}

// ── Label Generation ──────────────────────────────────────────────

export function generateLabel(
  credential: SignedCredential
): ComplianceLabel {
  const level = credential.payload.subject.aiAssistance;

  const labelMap: Record<AIAssistanceLevel, { label: Article50Label; description: string; requiresDisclosure: boolean }> = {
    none: {
      label: "human-only",
      description: "This content was created entirely by a human without AI assistance.",
      requiresDisclosure: false,
    },
    partial: {
      label: "ai-assisted",
      description: "This content was created by a human with AI assistance (e.g. research, editing).",
      requiresDisclosure: false,
    },
    "ai-assisted": {
      label: "ai-generated",
      description: "This content was drafted by AI and reviewed and approved by a human.",
      requiresDisclosure: true,
    },
    "fully-ai": {
      label: "ai-fully-generated",
      description: "This content was generated by AI without human review.",
      requiresDisclosure: true,
    },
  };

  const mapping = labelMap[level];

  return {
    label: mapping.label,
    description: mapping.description,
    aiAssistance: level,
    requiresDisclosure: mapping.requiresDisclosure,
    labeledAt: new Date().toISOString(),
    protocolVersion: "0.1.0",
  };
}

// ── Compliance Checking ───────────────────────────────────────────

export function checkCompliance(
  credential: SignedCredential | null
): ComplianceResult {
  const checkedAt = new Date().toISOString();
  const violations: string[] = [];

  if (!credential) {
    return {
      compliant: false,
      label: null,
      violations: ["No credential provided. Content has no authenticity provenance."],
      credential: null,
      checkedAt,
    };
  }

  if (!verifyCredentialSignature(credential)) {
    violations.push("Credential signature is invalid — possible tampering.");
  }

  const label = generateLabel(credential);

  if (
    credential.payload.type === "delegation" &&
    credential.payload.subject.aiAssistance === "fully-ai"
  ) {
    violations.push(
      "WARNING: Fully AI-generated content attributed to a human principal. " +
      "If this content depicts a real person, it may constitute a deepfake " +
      "requiring explicit disclosure under Article 50."
    );
  }

  return {
    compliant: violations.length === 0,
    label,
    violations,
    credential,
    checkedAt,
  };
}

export function checkUnregisteredContent(
  _content: string
): ComplianceResult {
  return {
    compliant: false,
    label: null,
    violations: [
      "Content has no authenticity credential. Under Article 50, " +
      "AI-generated content must be labeled. Without a credential, " +
      "compliance cannot be verified.",
    ],
    credential: null,
    checkedAt: new Date().toISOString(),
  };
}

// ── Machine-Readable Manifest ─────────────────────────────────────

export interface Article50Manifest {
  "@context": string;
  "type": string;
  "label": Article50Label;
  "description": string;
  "aiAssistance": AIAssistanceLevel;
  "requiresDisclosure": boolean;
  "issuer": string;
  "issuedAt": string;
  "contentHash": string | null;
  "signature": string;
  "labeledAt": string;
}

export function generateManifest(
  credential: SignedCredential
): Article50Manifest {
  const label = generateLabel(credential);

  return {
    "@context": "https://authenticity-os.org/article50/v1",
    "type": "Article50ComplianceLabel",
    "label": label.label,
    "description": label.description,
    "aiAssistance": label.aiAssistance,
    "requiresDisclosure": label.requiresDisclosure,
    "issuer": credential.payload.issuer,
    "issuedAt": credential.payload.issuedAt,
    "contentHash": credential.payload.subject.contentHash ?? null,
    "signature": credential.signature,
    "labeledAt": label.labeledAt,
  };
}

// ── HTML Meta Tag Generation ──────────────────────────────────────

export function generateMetaTags(
  credential: SignedCredential
): string[] {
  const manifest = generateManifest(credential);

  return [
    `<meta name="ai-content-label" content="${manifest.label}" />`,
    `<meta name="ai-content-description" content="${manifest.description}" />`,
    `<meta name="ai-content-issuer" content="${manifest.issuer}" />`,
    `<meta name="ai-content-hash" content="${manifest.contentHash ?? ""}" />`,
    `<meta name="ai-content-labeled" content="${manifest.labeledAt}" />`,
  ];
}
