/**
 * @auth/protocol — EU AI Act Article 50 compliance
 *
 * Article 50 of the EU AI Act requires that AI-generated or AI-manipulated
 * content be clearly labeled in a machine-readable way. Enforcement begins
 * August 2, 2026.
 *
 * This module provides:
 * 1. Compliance labeling — generates machine-readable compliance metadata
 *    from a credential's AI assistance level
 * 2. Compliance checking — verifies that content has proper labeling
 * 3. Article 50-specific credential types — wraps content credentials
 *    with compliance metadata
 */

import type {
  SignedCredential,
  AIAssistanceLevel,
} from "./types.js";
import {
  verifyCredentialSignature,
} from "./credentials.js";

// ── Compliance Types ──────────────────────────────────────────────

/** Article 50 label categories */
export type Article50Label =
  | "human-only"          // No AI involvement whatsoever
  | "ai-assisted"         // Human created with AI assistance (spell-check, research)
  | "ai-generated"        // AI drafted, human reviewed and approved
  | "ai-fully-generated"  // AI generated without human review
  | "deepfake"            // Synthetic media depicting real persons
  | "ai-manipulated";     // Real media altered by AI

/** Machine-readable compliance metadata */
export interface ComplianceLabel {
  /** The Article 50 category */
  label: Article50Label;
  /** Human-readable description for display */
  description: string;
  /** The original AI assistance level from the credential */
  aiAssistance: AIAssistanceLevel;
  /** Whether this content requires disclosure under Article 50 */
  requiresDisclosure: boolean;
  /** ISO 8601 timestamp of label generation */
  labeledAt: string;
  /** Protocol version that generated this label */
  protocolVersion: string;
}

/** Result of a compliance check */
export interface ComplianceResult {
  /** Whether the content is compliant (has proper labeling) */
  compliant: boolean;
  /** The compliance label, if found */
  label: ComplianceLabel | null;
  /** List of compliance violations */
  violations: string[];
  /** The credential examined */
  credential: SignedCredential | null;
  checkedAt: string;
}

// ── Label Generation ──────────────────────────────────────────────

/**
 * Generate a compliance label from a credential's AI assistance level.
 * Maps our internal AIAssistanceLevel to Article 50 categories.
 */
export function generateLabel(
  credential: SignedCredential
): ComplianceLabel {
  const level = credential.payload.subject.aiAssistance;

  const labelMap: Record<AIAssistanceLevel, { label: Article50Label; description: string; requiresDisclosure: boolean }> = {
    none: {
      label: "human-only",
      description: "This content was created entirely by a human without AI assistance.",
      requiresDisclosure: false,
    },
    partial: {
      label: "ai-assisted",
      description: "This content was created by a human with AI assistance (e.g. research, editing).",
      requiresDisclosure: false,
    },
    "ai-assisted": {
      label: "ai-generated",
      description: "This content was drafted by AI and reviewed and approved by a human.",
      requiresDisclosure: true,
    },
    "fully-ai": {
      label: "ai-fully-generated",
      description: "This content was generated by AI without human review.",
      requiresDisclosure: true,
    },
  };

  const mapping = labelMap[level];

  return {
    label: mapping.label,
    description: mapping.description,
    aiAssistance: level,
    requiresDisclosure: mapping.requiresDisclosure,
    labeledAt: new Date().toISOString(),
    protocolVersion: "0.1.0",
  };
}

// ── Compliance Checking ───────────────────────────────────────────

/**
 * Check whether a credential is compliant with EU AI Act Article 50.
 *
 * A credential is compliant if:
 * 1. It has a valid signature
 * 2. It discloses AI involvement when required
 * 3. The AI assistance level is accurately represented
 */
export function checkCompliance(
  credential: SignedCredential | null
): ComplianceResult {
  const checkedAt = new Date().toISOString();
  const violations: string[] = [];

  if (!credential) {
    return {
      compliant: false,
      label: null,
      violations: ["No credential provided. Content has no authenticity provenance."],
      credential: null,
      checkedAt,
    };
  }

  // 1. Signature check
  if (!verifyCredentialSignature(credential)) {
    violations.push("Credential signature is invalid — possible tampering.");
  }

  // 2. Generate label from credential
  const label = generateLabel(credential);

  // 3. Disclosure check — if AI was used, the credential must exist and disclose it
  if (label.requiresDisclosure) {
    // The credential itself IS the disclosure — its presence means the
    // content creator has attested to the AI assistance level.
    // This is compliant by design: the protocol IS the disclosure mechanism.
  }

  // 4. Check for deepfake indicators (heuristic — v0.1)
  // If the credential type is "delegation" with fully-ai, flag as potential deepfake risk
  if (
    credential.payload.type === "delegation" &&
    credential.payload.subject.aiAssistance === "fully-ai"
  ) {
    violations.push(
      "WARNING: Fully AI-generated content attributed to a human principal. " +
      "If this content depicts a real person, it may constitute a deepfake " +
      "requiring explicit disclosure under Article 50."
    );
  }

  return {
    compliant: violations.length === 0,
    label,
    violations,
    credential,
    checkedAt,
  };
}

/**
 * Check compliance for content without a credential.
 * Returns a non-compliant result — the content has no provenance.
 */
export function checkUnregisteredContent(
  content: string
): ComplianceResult {
  return {
    compliant: false,
    label: null,
    violations: [
      "Content has no authenticity credential. Under Article 50, " +
      "AI-generated content must be labeled. Without a credential, " +
      "compliance cannot be verified.",
    ],
    credential: null,
    checkedAt: new Date().toISOString(),
  };
}

// ── Machine-Readable Manifest ─────────────────────────────────────

/**
 * Generate a machine-readable compliance manifest for embedding in content metadata.
 * This is the format platforms can embed in HTML meta tags, JSON-LD, or C2PA manifests.
 */
export function generateManifest(
  credential: SignedCredential
): Article50Manifest {
  const label = generateLabel(credential);

  return {
    "@context": "https://authenticity-os.org/article50/v1",
    "type": "Article50ComplianceLabel",
    "label": label.label,
    "description": label.description,
    "aiAssistance": label.aiAssistance,
    "requiresDisclosure": label.requiresDisclosure,
    "issuer": credential.payload.issuer,
    "issuedAt": credential.payload.issuedAt,
    "contentHash": credential.payload.subject.contentHash ?? null,
    "signature": credential.signature,
    "labeledAt": label.labeledAt,
  };
}

export interface Article50Manifest {
  "@context": string;
  "type": string;
  "label": Article50Label;
  "description": string;
  "aiAssistance": AIAssistanceLevel;
  "requiresDisclosure": boolean;
  "issuer": string;
  "issuedAt": string;
  "contentHash": string | null;
  "signature": string;
  "labeledAt": string;
}

// ── HTML Meta Tag Generation ──────────────────────────────────────

/**
 * Generate HTML meta tags for Article 50 compliance.
 * Platforms can inject these into their HTML <head>.
 */
export function generateMetaTags(
  credential: SignedCredential
): string[] {
  const manifest = generateManifest(credential);

  return [
    `<meta name="ai-content-label" content="${manifest.label}" />`,
    `<meta name="ai-content-description" content="${manifest.description}" />`,
    `<meta name="ai-content-issuer" content="${manifest.issuer}" />`,
    `<meta name="ai-content-hash" content="${manifest.contentHash ?? ''}" />`,
    `<meta name="ai-content-labeled" content="${manifest.labeledAt}" />`,
  ];
}
