import { describe, it, expect } from "vitest";
import {
  createIdentity,
  attestCreation,
  vouchFor,
  delegateCreation,
  verifyCredentialSignature,
  isExpired,
  contentHash,
} from "../src/index.js";

describe("credentials", () => {
  it("attests content creation with a valid signature", () => {
    const alice = createIdentity("alice", "peer");
    const content = "My original human-written post";
    const hash = contentHash(content);
    const credential = attestCreation(alice, hash, "none", "screenshot");

    expect(credential.payload.type).toBe("creation");
    expect(credential.payload.issuer).toBe(alice.id);
    expect(credential.payload.subject.contentHash).toBe(hash);
    expect(credential.payload.subject.aiAssistance).toBe("none");
    expect(credential.signer).toBe(alice.id);
    expect(verifyCredentialSignature(credential)).toBe(true);
  });

  it("creates a vouch credential", () => {
    const alice = createIdentity("alice", "peer");
    const bob = createIdentity("bob", "peer");
    const vouch = vouchFor(alice, bob.id, "known personally for 5 years");

    expect(vouch.payload.type).toBe("vouch");
    expect(vouch.payload.subject.targetId).toBe(bob.id);
    expect(vouch.payload.subject.aiAssistance).toBe("none");
    expect(verifyCredentialSignature(vouch)).toBe(true);
  });

  it("creates a delegation credential for AI-assisted content", () => {
    const alice = createIdentity("alice", "peer");
    const content = "Draft generated by my AI agent";
    const hash = contentHash(content);
    const delegation = delegateCreation(alice, hash, "ai-assisted", "agent-draft-v1");

    expect(delegation.payload.type).toBe("delegation");
    expect(delegation.payload.subject.aiAssistance).toBe("ai-assisted");
    expect(delegation.payload.subject.evidence).toBe("agent-draft-v1");
    expect(verifyCredentialSignature(delegation)).toBe(true);
  });

  it("detects tampered credentials", () => {
    const alice = createIdentity("alice", "peer");
    const hash = contentHash("test content");
    const credential = attestCreation(alice, hash, "none");

    // Tamper with the content hash
    credential.payload.subject.contentHash = "fake-hash";
    expect(verifyCredentialSignature(credential)).toBe(false);
  });

  it("detects expired credentials", () => {
    const alice = createIdentity("alice", "peer");
    const hash = contentHash("test content");
    const credential = attestCreation(alice, hash, "none");

    // Set expiry in the past
    credential.payload.expiresAt = new Date(
      Date.now() - 1000
    ).toISOString();

    expect(isExpired(credential)).toBe(true);
  });

  it("does not expire credentials without expiry", () => {
    const alice = createIdentity("alice", "peer");
    const hash = contentHash("test content");
    const credential = attestCreation(alice, hash, "none");

    expect(isExpired(credential)).toBe(false);
  });
});
